/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Experience: typeof import('./src/components/Experience.vue')['default']
    IntroCard: typeof import('./src/components/IntroCard.vue')['default']
    SkillChart: typeof import('./src/components/SkillChart.vue')['default']
  }
}
